name: Build

on: workflow_dispatch

jobs:
   build:
    name: Build
    if: github.ref_name == github.event.repository.default_branch
    runs-on: Ubuntu-latest

    steps:
    - id: checkout
      name: Checkout repository
      uses: actions/checkout@v4
      
    - id: lint
      name: Code Analysis
      uses: ./.github/workflows/lint.yml
      
    - id: build
      name: Build app      
      run: |
        echo "build app step"
        echo "Result of lint: ${{ needs.lint.result }}"
