# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges

name: Build

on:
  pull_request:
    types:
      - closed

jobs:
  # lint:
    # name: Code Analysis
    # if: github.ref_name == github.event.repository.default_branch
    # uses: ./.github/workflows/lint.yml

  # test:
    # name: Test
    # uses: ./.github/workflows/test.yml
    
  build:
    name: Build
    # if: github.event.pull_request.merged == true && github.event.review.state == 'approved' && github.ref_name == github.event.repository.default_branch
    runs-on: Ubuntu-latest
    # needs: [lint, test]
    
    steps:
    - id: build
      name: Build app      
      run: |
        echo "build app step"
        echo "Request Merged = ${{  github.event.pull_request.merged }}"
        echo "Review State = ${{ github.event.review.state }}"
        echo "Default Branch = ${{ github.event.repository.default_branch }}"
        # echo "Result of lint: ${{ needs.lint.result }}"
        # echo "Result of test: ${{ needs.test.result }}"
