name: Build

on: workflow_dispatch

jobs:
  lint:
    name: Code Analysis
    if: github.ref_name == github.event.repository.default_branch
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    
  build:
    name: Build
    #if: github.ref_name == github.event.repository.default_branch
    runs-on: Ubuntu-latest
    needs: [lint, test]
    
    steps:
    - id: build
      name: Build app      
      run: |
        echo "build app step"
        echo "Result of lint: ${{ needs.lint.result }}"
        echo "Result of test: ${{ needs.test.result }}"
