name: Build

on: workflow_dispatch

jobs:
  test:
    name: Test
    if: github.ref_name == github.event.repository.default_branch
    uses: ./.github/workflows/lint.yml
    
  build:
    name: Build
    #if: github.ref_name == github.event.repository.default_branch
    runs-on: Ubuntu-latest
    needs: test
    
    steps:
    - id: build
      name: Build app      
      run: |
        echo "build app step"
        echo "Result of lint: ${{ needs.test.result }}"
