name: Online Example

on: workflow_dispatch

env:
  PROJECT_ID: project-python
  REPO: ${GITHUB_REPOSITORY##*/}
  REPOSITORY: ${REPO}repo-name
  REPO_NAME_1: ${REPO^^}
  REPO_NAME_2: ${GITHUB_REPOSITORY##*/^^}
  IMAGE: image-name
  REPO_NAME_3: ${REPO_NAME_1,,}-${IMAGE^}
  AR_LOCATION: us-central1
  AR_URL: ${AR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY##*/}
  SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
  SERVICE_ACCOUNT: ${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
  TEST_VARIABLE: ${{ vars.A_VARIABLE }}
  TEST_VARIABLE_2: ${{ vars.B_VARIABLE }}
  TEST_VARIABLE_3: ${{ vars.REPO_VARIABLE_2 }}

jobs:
  example:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GH_SHA_VARIABLE: ${GITHUB_SHA::8}
    steps:
      - uses: actions/checkout@v4

      - id: vars
        name: Set output        
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: get-tag-name
        name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - id: get-sha
        name: Get short sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}
          tags: |
            type=sha,format=short,prefix=

      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.short_ref }}
          echo ${{ github.ref_name }}
          echo ${GITHUB_SHA}
          echo ${{ github.sha }}
          echo ${{ env.SERVICE_ACCOUNT }}
          echo ${{ env.AR_URL }}
          echo ${{ secrets.SERVICE_ACCOUNT_NAME }}
          echo ${{ env.TEST_VARIABLE }}
          echo ${{ env.TEST_VARIABLE_2 }}
          echo "github.repository = ${{ github.repository }}"
          echo "GITHUB_REPOSITORY = ${GITHUB_REPOSITORY}"
          echo ${GITHUB_REPOSITORY##*/}
          echo "this is repo variable set env ${{ env.TEST_VARIABLE_3 }}"
          echo "this is repo varilable direct ${{ vars.REPO_VARIABLE_2 }}"
          echo "this is secret repo variable ${{ secrets.REPO_SECRET_VARIABLE_1 }}"
          echo "default_branch value is $default-branch"
          echo "github ref value ${GITHUB_REF}"
          echo "github ref value slice ${GITHUB_REF#refs/*/}"
          echo "github sha as env variable ${{ env.GH_SHA_VARIABLE }}"
          echo "github sha direct reference ${GITHUB_SHA::8}"
          echo "github sha context ${{ github.sha }}"
          echo "get tag name ${{ steps.get-tag-name.outputs.TAG_NAME }}"
          echo "get short sha ${{ steps.get-sha.outputs.sha_short }}"
          REPO_NAME_4=${GITHUB_REPOSITORY##*/}
          REPO_NAME_4=${REPO_NAME_4^^}         
          echo "REPO_NAME_4 = ${REPO_NAME_4}"
          echo "REPO_NAME_1 = ${REPO_NAME_1}"
          echo "REPO_NAME_3 = ${REPO_NAME_3}"
          echo "REPO_NAME_2 = ${REPO_NAME_2}"
          echo "Docker meta sha tag ${{ steps.meta.outputs.tags }}"
          echo "Docker meta label ${{ steps.meta.outputs.labels }}"
