name: Online Example

on: workflow_dispatch

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: vars
        name: Set output        
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.short_ref }}
          echo ${{ github.ref_name }}
