name: Online Example

on: workflow_dispatch

env:
  PROJECT_ID: project-python
  REPO: ${GITHUB_REPOSITORY}
  REPOSITORY: ${REPO}repo-name
  IMAGE: image-name
  AR_LOCATION: us-central1
  AR_URL: ${AR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY##*/}
  SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
  SERVICE_ACCOUNT: ${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
  TEST_VARIABLE: ${{ vars.A_VARIABLE }}
  TEST_VARIABLE_2: ${{ vars.B_VARIABLE }}
  TEST_VARIABLE_3: ${{ vars.REPO_VARIABLE_2 }}

jobs:
  example:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - id: vars
        name: Set output        
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.short_ref }}
          echo ${{ github.ref_name }}
          echo ${GITHUB_SHA}
          echo ${{ github.sha }}
          echo ${{ env.SERVICE_ACCOUNT }}
          echo ${{ env.AR_URL }}
          echo ${{ secrets.SERVICE_ACCOUNT_NAME }}
          echo ${{ env.TEST_VARIABLE }}
          echo ${{ env.TEST_VARIABLE_2 }}
          echo ${{ github.repository }}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_REPOSITORY##*/}
          echo "this is repo variable set env ${{ env.TEST_VARIABLE_3 }}"
          echo "this is repo varilable direct ${{ vars.REPO_VARIABLE_2 }}"
          echo "this is secret repo variable ${{ secrets.REPO_SECRET_VARIABLE_1 }}"
          echo "default_branch value is $default-branch"
