name: Code Analysis

on: 
  # push:
    # paths:
      # - '**.py'

  pull_request:
    branches:
      - main
    # paths:
      # - '**.py'

  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with: 
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - id: py-file-list
      name: Set changed Python file list
      run: |
        git fetch origin ${{ env.DEFAULT_BRANCH }}
        git diff --name-only origin/${{ env.DEFAULT_BRANCH }}...HEAD | grep '\.py$' > py_file_list.txt || true

    - name: Show py file list
      run: cat py_file_list.txt

    - name: Analysing the code with pylint
      if: success() && steps.py-file-list.outputs.py_file_list != ''
      run: >
        make lint \
          PY_FILE_LIST=$(cat py_file_list.txt)
