name: Code Analysis

on: 
  # push:
    # paths:
      # - '**.py'

  pull_request:
    branches:
      - main
    # paths:
      # - '**.py'

  workflow_dispatch:
    inputs:
      lint_mode:
        description: 'Choose linting mode'
        required: true
        default: 'changed'
        type: choice
        options:
          - changed
          - all

  workflow_call:

permissions:
  contents: read

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  PYTHON_VERSION: "3.10"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with: 
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - id: py-file-list
      name: Set Python file list
      run: |
        if [ "${{ github.event.inputs.lint_mode }}" == "changed" ]; then
          git fetch origin ${{ env.DEFAULT_BRANCH }}
          git diff --name-only origin/${{ env.DEFAULT_BRANCH }}...HEAD | grep '\.py$' > py_file_list.txt || true
          if [ ! -s py_file_list.txt ]; then
            echo "No Python file(s) changed."
            exit 0
          fi
        elif [ "${{ github.event.inputs.lint_mode }}" == "all" ]; then
          find * -type f -iname '*.py' > py_file_list.txt || true
          if [ ! -s py_file_list.txt ]; then
            echo "No Python file(s) found."
            exit 0
          fi
        fi

    - name: Analysing the code with pylint
      if: success() && steps.py-file-list.outputs.py_file_list != ''
      run: >
        make lint \
          PY_FILE_LIST="$(cat py_file_list.txt | tr '\n' ' ')"
