name: Pre-Merge Check

on: 
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  lint:
    name: Code Analysis
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml
 
  status:
    name: Status
    runs-on: Ubuntu-latest
    needs: [lint, test]

    steps:
      - id: show-status
        name: Show Status
        run: |
          echo "Show workflow status"
          echo "Result of lint: ${{ needs.lint.result }}"
          echo "Result of test: ${{ needs.test.result }}"
