name: reusable-pylint

on:
  workflow_call:
    inputs:
      default-branch:
        description: "Default Branch"
        required: true
        type: string

      python-version:
        description: "Python Version"
        required: true
        type: string

      lint-path:
        description: "Lint Path"
        required: true
        type: string

      lint-mode:
        description: "Lint Mode"
        required: true
        type: string

permissions:
  contents: read

env:
  DEFAULT_BRANCH: ${{ inputs.default-branch }}
  PYTHON_VERSION: ${{ inputs.python-version }}
  LINT_MODE: ${{ inputs.lint-mode }}
  LINT_PATH: ${{ inputs.lint-path }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        cd ${{ env.LINT_PATH }}
        pwd
        python -m pip install --upgrade pip
        pip install pylint

    - id: py-file-list
      name: Set changed Python file list
      run: |
        if [ "${{ env.LINT_MODE }}" == "" ] || [ "${{ env.LINT_MODE }}" == "changed" ]; then
          git fetch origin ${{ env.DEFAULT_BRANCH }}
          git diff --name-only --diff-filter=d origin/${{ env.DEFAULT_BRANCH }}...HEAD ${{ env.LINT_PATH }} | grep '\.py$' > py_file_list.txt || true
          #git diff --name-only --diff-filter=d HEAD^ ${{ env.LINT_PATH }} | grep '\.py$' > py_file_list.txt || true
          if [ ! -s py_file_list.txt ]; then
            echo "No Python file(s) changed."
            exit 0
          fi
        else
          find ${{ env.LINT_PATH }} -type f -iname '*.py' > py_file_list.txt || true
          if [ ! -s py_file_list.txt ]; then
            echo "No Python file(s) found."
            exit 0
          fi
        fi
        echo "RUN_LINT=true" >> $GITHUB_OUTPUT
        echo "Python file(s) to analyze: "
        cat py_file_list.txt
        #git diff --name-only --diff-filter=d HEAD^ ${{ env.LINT_PATH }}

    - name: Analysing the code with pylint
      if: ${{ success() && steps.py-file-list.outputs.RUN_LINT }}
      run: |
        echo "pylint $(cat py_file_list.txt | tr '\n' ' ')"
        pylint $(cat py_file_list.txt | tr '\n' ' ')

