name: service-svc1-pylint

on:
  pull_request:
    paths:
      - 'service/svc1/**'

  workflow_dispatch:
    inputs:
      lint_mode:
        description: 'Choose linting mode'
        required: true
        default: 'changed'
        type: choice
        options:
          - changed
          - all

jobs:
  call-lint:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      default-branch: ${{ github.event.repository.default_branch }}
      python-version: '3.10'
      lint-path: 'service/svc1/'
      lint-mode: ${{ github.event.inputs.lint_mode }}
