name: service-svc2-pylint

on:
  pull_request:
    paths:
      - 'service/svc2/**'

  workflow_dispatch:
    inputs:
      lint_mode:
        description: 'Choose linting mode'
        required: true
        default: 'changed'
        type: choice
        options:
          - changed
          - all

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml@main
    with:
      lint-path: 'service/svc2/'
      lint-mode: ${{ github.event.inputs.lint_mode }}

