name: Trial

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  trial:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: py-file-list
      name: Set py file list
      run: |
        echo "HELLO_WORLD='hello world'" >> $GITHUB_OUTPUT

    - name: Show variables
      run: |
        echo "GITHUB_BASE_REF = ${GITHUB_BASE_REF}"
        echo "GITHUB_HEAD_REF = ${GITHUB_HEAD_REF}"
        echo "HELLO_WORLD = ${{ steps.py-file-list.outputs.HELLO_WORLD }}"
        echo "GITHUB_REF_NAME = ${GITHUB_REF_NAME}"
        echo "github.event.repository.default_branch = ${{ github.event.repository.default_branch }}"
        echo "GITHUB_REF = ${GITHUB_REF}"
        echo "GITHUB_SHA = ${GITHUB_SHA}"
        echo "git ls-files"
        git ls-files
        echo "git ls-files --unmerged"
        git ls-files --unmerged
        echo "git ls-files --stage"
        git ls-files --stage
        echo "git diff --name-only ${GITHUB_HEAD_REF}"
        git diff --name-only $GITHUB_HEAD_REF
        echo "git diff --name-only ${GITHUB_BASE_REF} ${GITHUB_HEAD_REF}"
        git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF
