name: Trial

on:
  workflow_dispatch:

jobs:
  trial:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/scripts@v7    
      with:
        scripts: echo "Hello World"

